### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by l4km47** [l4km47/TubeDl#8]
- [x] Multiple downloads
- [x] new GUI 
- [x] Download dialog's
- [x] Catch copied link automatically 
- [x] Download later option
- [x] Pause / Resume improved 
- [x] Downloading improved 
- [x] Separate to dll's
- [ ] No audio on 1080p 240p and 480p videos. #6
- [x] Listview colore changing fix
- [ ] Download corruption after connection lost #9
- [ ] More than youtube #10
   - [ ] Facebook 
   - [ ] Instagram
